TemplateName: 'business-license-ocr-template'

Targets:
  - Name: "统一社会信用代码"
    RecognitionType: "horizontal"
    KeyWordList: ["统一社会信用代码"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.3
    XRangeMax: 0.80
    YRangeMin: 0.0
    YRangeMax: 0.50

  - Name: "名称"
    RecognitionType: "horizontal"
    KeyWordList: ["名称"]
    MinLength: 20
    MaxLength: 30
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.3
    YRangeMax: 0.60

  - Name: "类型"
    RecognitionType: "horizontal"
    KeyWordList: ["类型"]
    MinLength: 20
    MaxLength: 30
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.3
    YRangeMax: 0.60

  - Name: "住所"
    RecognitionType: "horizontal"
    KeyWordList: ["住所"]
    MinLength: 20
    MaxLength: 30
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.3
    YRangeMax: 0.60


  - Name: "法定代表人"
    RecognitionType: "horizontal"
    KeyWordList: ["法定代表人"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.2
    YRangeMax: 0.6

  - Name: "注册资本"
    RecognitionType: "horizontal"
    KeyWordList: ["注册资本"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.80
    YRangeMin: 0.3
    YRangeMax: 0.7


  - Name: "成立日期"
    RecognitionType: "horizontal"
    KeyWordList: ["成立日期"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.80
    YRangeMin: 0.3
    YRangeMax: 0.7


  - Name: "营业期限"
    RecognitionType: "horizontal"
    KeyWordList: ["营业期限"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.80
    YRangeMin: 0.3
    YRangeMax: 0.8


  - Name: "经营范围"
    RecognitionType: "horizontal"
    KeyWordList: ["经营范围"]
    MinLength: 20
    MaxLength: 20
    MaxLineCount: 4
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.80
    YRangeMin: 0.4
    YRangeMax: 0.8
