TemplateName: 'business-license-ocr-template'

Targets:
  - Name: "二维码"
    RecognitionType: "qrcode"
    XRangeMax: 0.3
    YRangeMin: 0.70
    YRangeMax: 0.9
  - Name: "统一社会信用代码"
  - Name: "注册号"
  - Name: "名称"
    KeyWordList: ["称"]
  - Name: "类型"
  - Name: "住所"
  - Name: "经营场所"
  - Name: "组成形式"
  - Name: "法定代表人"
  - Name: "注册资本"
  - Name: "成立日期"
    KeyWordList: ["注册日期"]
  - Name: "营业期限"
    LengthMax: 20
  - Name: "经营范围"
    LineCountMax: 4
    TopOffsetRadio: -1.0
    LeftOffsetRadio: -1.0
    RightOffsetRadio: 5
    BottomOffsetRadio: 3.0