TemplateName: 'business-license-ocr-template'

DefaultValue:
  KeyValue:
    LeftOffsetRadio: -1.01
Targets:
  - Name: "法定代表人"

  - Name: "类型"
    KeyWordList: ["型"]


  - Name: "统一社会信用代码"
  - Name: "注册号"
  - Name: "名称"
    KeyWordList: ["称"]


  - Name: "住所"
    KeyWordList: ["所"]
  - Name: "经营场所"
  - Name: "组成形式"

  - Name: "注册资本"
  - Name: "成立日期"
    KeyWordList: ["注册日期"]
  - Name: "营业期限"
    LengthMax: 20
  - Name: "经营范围"
    LineCountMax: 4
    LengthMax: 400
    TopOffsetRadio: -1.0
    LeftOffsetRadio: -1.0
    RightOffsetRadio: 5
    BottomOffsetRadio: 3.0