TemplateName: 'business-license-ocr-template'

Targets:
  - Name: "二维码"
    RecognitionType: "qrcode"
    XRangeMin: 0.70
    XRangeMax: 0.85
    YRangeMin: 0.25
    YRangeMax: 0.40
  - Name: "统一社会信用代码"
    TopOffsetRadio: 1.0
    LeftOffsetRadio: -1.0
    RightOffsetRadio: 0.5
    BottomOffsetRadio: 4.0
  - Name: "名称"
    KeyWordList: ["称"]
    RightOffsetRadio: 20

  - Name: "类型"
    KeyWordList: ["型"]
    RightOffsetRadio: 20

  - Name: "法定代表人"
  - Name: "经营范围"
    LineCountMax: 4
    RightOffsetRadio: 3
  - Name: "注册资本"
  - Name: "成立日期"
  - Name: "营业期限"
  - Name: "住所"
    KeyWordList: ["所"]
    LineCountMax: 2