TemplateName: 'hospital-ocr-template'

Targets:
  - Name: "交易流水号"
    KeyWordList: ["交易流水号"]
    MinLength: 18
    MaxLength: 25
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.0
    YRangeMax: 0.30
    
  - Name: "上传NO"
    KeyWordList: ["上传NO："]
    MinLength: 12
    MaxLength: 12
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.5
    XRangeMax: 1.0
    YRangeMin: 0.0
    YRangeMax: 0.30
    
  - Name: "姓名"
    KeyWordList: ["姓名"]
    MinLength: 2
    MaxLength: 6
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.0
    YRangeMax: 0.30

  - Name: "性别"
    KeyWordList: ["性别","性别：","性别:"]
    MinLength: 1
    MaxLength: 1
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.10
    YRangeMax: 0.40

  - Name: "医保类型"
    KeyWordList: ["医保类型","医保类型：","医保类型:"]
    MinLength: 2
    MaxLength: 6
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.5
    YRangeMin: 0.10
    YRangeMax: 0.50


  - Name: "社会保障号码"
    KeyWordList: ["社会保障号码","社会保障号码：","社会保障号码:"]
    MinLength: 10
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.70
    YRangeMin: 0.10
    YRangeMax: 0.60

  - Name: "合计"
    KeyWordList: ["合计","合计（大写）："]
    MinLength: 2
    MaxLength: 30
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.90
    YRangeMin: 0.10
    YRangeMax: 0.80

  - Name: "基金"
    KeyWordList: ["基金"]
    MinLength: 1
    MaxLength: 10
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.70
    YRangeMin: 0.50
    YRangeMax: 1.0
    
  - Name: "个人支付金额"
    KeyWordList: ["个人支付金额","个人支付金额：","个人支付金额:"]
    MinLength: 1
    MaxLength: 10
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 1.0
    YRangeMin: 0.50
    YRangeMax: 1.0

  - Name: "自付一"
    KeyWordList: ["自付一："]
    MinLength: 1
    MaxLength: 10
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 1.0
    YRangeMin: 0.50
    YRangeMax: 1.0
    
  - Name: "自付二"
    KeyWordList: ["自付二："]
    MinLength: 1
    MaxLength: 10
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 1.0
    YRangeMin: 0.50
    YRangeMax: 1.0