template-name: 'id-ocr-template'

target:
  - name: "姓名"
    recognition-type: "horizontal"
    key-word-list: ["姓名", "名字"]
    min-length: 2
    max-length: 6
    target-value-type: "char"
    x-range-min: 0
    x-range-max: 40
    y-range-min: 0
    y-range-max: 40

  - name: "出生"
    recognition-type: "horizontal"
    # 百分比
    x-range-min: 0
    x-range-max: 100

