TemplateName: 'identity-card'
Targets:
  - Name: "姓名"
  - Name: "性别"
    LengthMax: 1
  - Name: "民族"
  - Name: "出生日期"
    KeyWordList: ["出生"]
  - Name: "住址"
    LineCountMax: 2
    LeftOffsetRadio: -1.0
    BottomOffsetRadio: 3.0
  - Name: "公民身份号码"