TemplateName: 'invoice-ocr-template'

Targets:
  - Name: "姓名"
    RecognitionType: "horizontal"
    KeyWordList: ["姓名", "名字"]
    MinLength: 2
    MaxLength: 6
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.30
    YRangeMin: 0.0
    YRangeMax: 0.30

  - Name: "购买方-纳税人识别号"
    RecognitionType: "horizontal"
    KeyWordList: ["纳税人识别号"]
    # 百分比
    MinLength: 16
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.10
    YRangeMax: 0.40

  - Name: "销售方-纳税人识别号"
    RecognitionType: "horizontal"
    KeyWordList: ["纳税人识别号"]
    # 百分比
    MinLength: 16
    MaxLength: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.50
    YRangeMax: 0.90

  - Name: "购买方-开户行及账号"
    RecognitionType: "horizontal"
    KeyWordList: ["开户行及账号"]
    # 百分比
    MinLength: 40
    MaxLength: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.10
    YRangeMax: 0.40

  - Name: "销售方-开户行及账号"
    RecognitionType: "horizontal"
    KeyWordList: ["开户行及账号"]
    # 百分比
    MinLength: 40
    MaxLength: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.50
    YRangeMax: 0.90


  - Name: "价税合计"
    RecognitionType: "horizontal"
    KeyWordList: ["价税合计（大写）"]
    # 百分比
    MinLength: 40
    MaxLength: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.30
    YRangeMax: 0.80