TemplateName: 'invoice-ocr-template'

Targets:
  - Name: "购买方-名称"
    RecognitionType: "default"
    KeyWordList: ["称：","称:"]
    LengthMin: 16
    LengthMax: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.10
    YRangeMax: 0.40

  - Name: "购买方-纳税人识别号"
    RecognitionType: "default"
    KeyWordList: ["纳税人识别号"]
    LengthMin: 16
    LengthMax: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.10
    YRangeMax: 0.40

  - Name: "购买方-开户行及账号"
    RecognitionType: "default"
    KeyWordList: ["开户行及账号"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.10
    YRangeMax: 0.40


  - Name: "销售方-名称"
    RecognitionType: "default"
    KeyWordList: ["称：","称:"]
    LengthMin: 16
    LengthMax: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.50
    YRangeMax: 0.90

  - Name: "销售方-纳税人识别号"
    RecognitionType: "default"
    KeyWordList: ["纳税人识别号"]
    LengthMin: 16
    LengthMax: 20
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.50
    YRangeMax: 0.90


  - Name: "销售方-开户行及账号"
    RecognitionType: "default"
    KeyWordList: ["开户行及账号"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.50
    YRangeMax: 0.90


  - Name: "价税合计（大写）"
    RecognitionType: "default"
    KeyWordList: ["价税合计（大写）"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.60
    YRangeMin: 0.30
    YRangeMax: 0.80

  - Name: "价税合计-小写"
    RecognitionType: "default"
    KeyWordList: ["（小写）"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.6
    XRangeMax: 1.0
    YRangeMin: 0.40
    YRangeMax: 0.70

  - Name: "发票代码"
    RecognitionType: "default"
    KeyWordList: ["发票代码"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.6
    XRangeMax: 1.0
    YRangeMin: 0.00
    YRangeMax: 0.30
  - Name: "发票号码"
    RecognitionType: "default"
    KeyWordList: ["发票号码"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.6
    XRangeMax: 1.0
    YRangeMin: 0.00
    YRangeMax: 0.40

  - Name: "开票日期"
    RecognitionType: "default"
    KeyWordList: ["开票日期"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.6
    XRangeMax: 1.0
    YRangeMin: 0.00
    YRangeMax: 0.40

  - Name: "校验码"
    RecognitionType: "default"
    KeyWordList: ["校验码"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.6
    XRangeMax: 1.0
    YRangeMin: 0.10
    YRangeMax: 0.50

  - Name: "机器编码"
    RecognitionType: "default"
    KeyWordList: ["机器编码"]
    LengthMin: 40
    LengthMax: 40
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.3
    YRangeMin: 0.10
    YRangeMax: 0.50


