TemplateName: 'hospital-ocr-template'

Targets:
  - Name: "交易流水号"
    TopOffsetRadio: -0.5
  - Name: "业务流水号"
    TopOffsetRadio: -0.8
    BottomOffsetRadio: 0.8
  - Name: "医疗机构类型"
    LeftOffsetRadio: -0.5
    TopOffsetRadio: -0.8
    BottomOffsetRadio: 0.8
  - Name: "上传NO"
  - Name: "姓名"
  - Name: "性别"
    KeyWordList: ["性别：", "性别:", "*性别"]
    TopOffsetRadio: -1.0
    BottomOffsetRadio: 1
    LengthMax: 1
  - Name: "医保类型"
    TopOffsetRadio: -0.3
    BottomOffsetRadio: 0.3
  - Name: "社会保障号码"
    KeyWordList: ["社会保障卡号"]
  - Name: "NO"
    KeyWordList: ["NO.", "*NO"]
    TopOffsetRadio: -1.5
    BottomOffsetRadio: 1.5
  - Name: "合计（大写）"
    KeyWordList: ["*大写"]
    RightOffsetRadio: 4.0
  - Name: "基金支付"
  - Name: "个人支付金额"
    KeyWordList: ["个人支付金额"]
    LeftOffsetRadio: 2
    TopOffsetRadio: -1.0
    BottomOffsetRadio: 1.5
  - Name: "门诊大额支付"
    ValueType: "number"
    TopOffsetRadio: -0.5
    BottomOffsetRadio: 0.5
  - Name: "退休补充支付"
    ValueType: "number"
    TopOffsetRadio: -0.5
    BottomOffsetRadio: 0.5
  - Name: "自付一"
    KeyWordList: ["*自付一：", "*自付一:", "自付一"]
  - Name: "自付二"
    KeyWordList: ["*自付二：", "*自付二:", "*自付二"]
  - Name: "收费项目一"
    RecognitionType: "Table"
    MaxRowHeightRatio: 2.0
    Columns:
      - ColumnName: "项目/规格"
#        KeyWordList: ["项目规格"]
        Location: true
        MainColumn: true
        MarginLeftType: "near"
        MoveLeftRatio: -0.3
        MarginRightType: "near"
        MoveRightRatio: 2.0
        XRangeMin: 0.0
        XRangeMax: 0.4
        YRangeMin: 0.1
        YRangeMax: 0.8

      - ColumnName: "单价"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 2.0
        ValueType: "number"
        Location: true
        XRangeMin: 0.1
        XRangeMax: 0.7
        YRangeMin: 0.1
        YRangeMax: 0.9

      - ColumnName: "数量/单位"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.1
        XRangeMin: 0.1
        XRangeMax: 0.5
        YRangeMin: 0.2
        YRangeMax: 0.8

      - ColumnName: "金额"
        KeyWordList: ["全额"]
        MarginLeftType: "near"
        MoveLeftRatio: -1.0
        MarginRightType: "near"
        MoveRightRatio: 2.0
        ValueType: "number"
        XRangeMin: 0.1
        XRangeMax: 0.7
        YRangeMin: 0.1
        YRangeMax: 0.9

      - ColumnName: "等级"
        KeyWordList: ["手级","登记","级"]
        MarginLeftType: "near"
        MoveLeftRatio: -1
        MarginRightType: "near"
        MoveRightRatio: 1.0
        Location: true
        XRangeMin: 0.1
        XRangeMax: 0.7
        YRangeMin: 0.1
        YRangeMax: 0.9

  - Name: "收费项目二"
    RecognitionType: "Table"
    MaxRowHeightRatio: 2.0
    Columns:
      - ColumnName: "项目/规格"
        Location: true
        MainColumn: true
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 1.0
        XRangeMin: 0.4
        XRangeMax: 0.8
        YRangeMin: 0.2
        YRangeMax: 0.8

      - ColumnName: "单价"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 2.0
        ValueType: "number"
        XRangeMin: 0.6
        XRangeMax: 0.9
        YRangeMin: 0.2
        YRangeMax: 0.8

      - ColumnName: "数量/单位"
        Location: true
        MarginRightType: "near"
        MoveRightRatio: 0.1
        XRangeMin: 0.6
        XRangeMax: 1.0
        YRangeMin: 0.2
        YRangeMax: 0.8

      - ColumnName: "金额"
        KeyWordList: ["全额"]
        Location: true
        MarginLeftType: "near"
        MoveLeftRatio: -1
        MarginRightType: "near"
        MoveRightRatio: 1.0
        ValueType: "number"
        XRangeMin: 0.6
        XRangeMax: 1.0
        YRangeMin: 0.2
        YRangeMax: 0.8

      - ColumnName: "等级"
        KeyWordList: ["手级","登记","级"]
        Location: true
        MarginRightType: "near"
        MoveRightRatio: 1
        MarginLeftType: "near"
        MoveLeftRatio: -1
        XRangeMin: 0.6
        XRangeMax: 1.0
        YRangeMin: 0.2
        YRangeMax: 0.8