TemplateName: 'table-ocr-template'

Targets:
  - Name: "公司名称"
    RecognitionType: "horizontal"
    KeyWordList: ["公司名称"]
    TargetValueType: "char"
    LengthMax: 30

  - Name: "纳税人识别号"
    RecognitionType: "horizontal"
    KeyWordList: ["纳税人识别号"]
    TargetValueType: "char"
    LengthMax: 30

  - Name: "打印人"
    RecognitionType: "horizontal"
    KeyWordList: ["打印人", "打印人：", "打印人:"]
    LengthMin: 2
    LengthMax: 30
    MaxLineCount: 1
    TargetValueType: "char"
    XRangeMin: 0.0
    XRangeMax: 0.40
    YRangeMin: 0.0
    YRangeMax: 0.50

  - Name: "分店"
    RecognitionType: "horizontal"
    KeyWordList: ["分店"]
    TargetValueType: "char"
    LengthMax: 30

  - Name: "打印时间"
    RecognitionType: "horizontal"
    KeyWordList: ["打印时间"]
    TargetValueType: "char"
    LengthMax: 20

  - Name: "结算单号"
    RecognitionType: "horizontal"
    KeyWordList: ["结算单号"]
    TargetValueType: "char"
    LengthMax: 20

  - Name: "结算年月"
    RecognitionType: "horizontal"
    KeyWordList: ["结算年月"]
    TargetValueType: "char"
    LengthMax: 20

  - Name: "供应商名称"
    RecognitionType: "horizontal"
    KeyWordList: ["供应商名称"]
    TargetValueType: "char"
    LengthMax: 40

  - Name: "结算费用单明细"
    RecognitionType: "table"
    # 用来做行切分的 '列' 的索引
    MainColumnIndex: 0
    # 用来迭代查找的行高， 以Column为基础 * MaxRowHeightRatio
    MaxRowHeightRatio: 2.5
    # 最大行数
    MaxRowCount: 5
    Columns:
        # 表格的显示名称
      - ColumnName: "扣款代码"

        # 通过  begin end 两个列 对表格的表头进行定位
        IndexType: "begin"

        # 可能出现的关键字
        KeyWordList: ["扣代码","扣款代码"]

        #  char  or  digit
        TargetValueType: "char"

        # MarginLeftType 说明
        # 1:  以Column 左边作为列的划分                 范围最近
        # 2:  以Column 到下一个Column 中点             中间范围
        # 3:  以Column 左边Column元素的右边作为分界点    范围最远


        MarginLeftType: 1
        # 在MarginLeftType 基础上， 往左移动的比率， 可以为负值。 比率需要乘以Column 的宽度
        MoveLeftRatio: -0.2

        # MarginRightType 说明
        # 1:  以Column 右边作为列的划分                 范围最近
        # 2:  以Column 到下一个Column 中点             中间范围
        # 3:  以Column 右边Column元素的左边作为分界点    范围最远

        MarginRightType: 1
        # 在MarginRightType 基础上  往右移动的比率， 可以为负值。 比率需要乘以Column 的宽度
        MoveRightRatio: 0.2
        XRangeMin: 0.1
        XRangeMax: 1.0
        YRangeMin: 0.1
        YRangeMax: 1.0

      - ColumnName: "费用项目"
        IndexType: "default"
        KeyWordList: ["费用项目"]
        TargetValueType: "char"
        MarginLeftType: 2
        MoveLeftRatio: -0.3
        MarginRightType: 2
        MoveRightRatio: 0.3

      - ColumnName: "扣款项目名称"
        IndexType: "default"
        KeyWordList: ["扣款项目名称"]
        TargetValueType: "char"
        XRangeMin: 0.2
        XRangeMax: 0.9
        YRangeMin: 0.1
        YRangeMax: 0.8

      - ColumnName: "扣款金额"
        IndexType: "end"
        KeyWordList: ["扣款额","扣款金额"]
        TargetValueType: "char"
        MarginLeftType: 2
        MoveLeftRatio: -0.2
        MarginRightType: 3
        MoveRightRatio: 0.1
        XRangeMin: 0.5
        XRangeMax: 1.0
        YRangeMin: 0.2
        YRangeMax: 0.7