TemplateName: 'table-ocr-template'

Targets:
  - Name: "供应商"
  - Name: "供应商名称"
  - Name: "结算费用单明细"
    RecognitionType: "table"
    MaxRowHeightRatio: 5.0
    Columns:

      - ColumnName: "单据号"
        MarginLeftType: "far"
        MoveLeftRatio: -1
        MarginRightType: "middle"
        MoveRightRatio: 0.5

      - ColumnName: "店号"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.5

      - ColumnName: "部门"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.5

      - ColumnName: "费用分类"
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.5


      - ColumnName: "扣费类型"
        MarginLeftType: "middle"
        MoveLeftRatio: -0.5
        MarginRightType: "middle"
        MoveRightRatio: 0.5


      - ColumnName: "方式"
        MarginLeftType: "middle"
        MoveLeftRatio: -0.5
        MarginRightType: "middle"
        MoveRightRatio: 0.5


      - ColumnName: "征收日期"
        MarginLeftType: "middle"
        MoveLeftRatio: -0.5
        MarginRightType: "middle"
        MoveRightRatio: 0.5


      - ColumnName: "应收金额"
        Location: true
        MainColumn: true
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.5

      - ColumnName: "应缴金额"
        Location: true
        MarginLeftType: "near"
        MoveLeftRatio: -0.5
        MarginRightType: "near"
        MoveRightRatio: 0.5

      - ColumnName: "摘要"
        MarginLeftType: "far"
        MoveLeftRatio: -0.1
        MarginRightType: "near"
        MoveRightRatio: 0.5